# test all modules
python Record.py
python check_gradient.py
python dataset_outliers.py
python dataset_sparse.py
python features.py
python learning_rate.py
python line_search.py
python loss_hinge.py
python loss_log.py
python loss_squared.py
python loss_squared_vw.py
python loss_quantile.py
python model_multiclass.py
python model_ols.py
python model_ridge.py
python module_linear.py
python module_linear_n.py
python module_negative_likelihood.py
python module_softmax.py
python numeric_gradient.py
python numpy_utilities.py
python random_sample.py
python regularizer_l1.py
python regularizer_l2.py
python test_function.py
